# Generated by Django 3.0.7 on 2020-06-20 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cities',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main_app.City'),
            preserve_default=False,
        ),
    ]
