# Generated by Django 3.0.7 on 2020-06-20 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200620_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main_app.City'),
        ),
    ]
